services:
  postgres:
    container_name: postgres-tru
    image: postgres
    environment:
      POSTGRES_USER: chis
      POSTGRES_PASSWORD: chis
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: trugarden_db
    volumes:
      - postgres:/data/postgres
    ports:
      - 5433:5432
    networks:
      - trugarden_network
    restart: unless-stopped

  mail-dev:
    container_name: mail-dev-tru
    image: maildev/maildev
    ports:
      - 1080:1080  # For UI
      - 1025:1025  # For SMTP server
    networks:
      - trugarden_network

networks:
  trugarden_network:
    driver: bridge

volumes:
  postgres:
    driver: local