create table role (
    id bigint generated by default as identity primary key,
    name varchar(255),
    created_date timestamp not null,
    last_modified_date timestamp,
    constraint uk_role_name unique (name)
);
