create table _user (
    id bigint generated by default as identity primary key,
    firstname varchar(255),
    lastname varchar(255),
    date_of_birth date,
    image varchar(255),
    email varchar(255),
    password varchar(255),
    account_locked boolean not null,
    enabled boolean not null,
    google_id varchar(255),
    auth_provider varchar(255),
    created_date timestamp not null,
    last_modified_date timestamp,
    constraint uk_user_email unique (email)
);

create table _user_roles (
    user_id bigint not null,
    roles_id bigint not null,
    primary key (user_id, roles_id),
    constraint fk_user_roles_user foreign key (user_id) references _user(id),
    constraint fk_user_roles_role foreign key (roles_id) references role(id)
);

create table address (
    id bigint generated by default as identity primary key,
    principal_street varchar(255),
    secondary_street varchar(255),
    first_name varchar(100),
    last_name varchar(100),
    email varchar(150),
    phone_number varchar(10),
    house_number varchar(10),
    zip_code varchar(15),
    sector varchar(255),
    city varchar(100),
    user_id bigint,
    session_id varchar(255),
    constraint fk_address_user foreign key (user_id) references _user(id)
);

create table token (
    id bigint generated by default as identity primary key,
    token varchar(255),
    created_at timestamp,
    expires_at timestamp,
    validated_at timestamp,
    user_id bigint not null,
    constraint fk_token_user foreign key (user_id) references _user(id)
);

create table wish_list (
    id bigint generated by default as identity primary key,
    user_id bigint,
    created_date timestamp not null,
    last_modified_date timestamp,
    constraint fk_wish_list_user foreign key (user_id) references _user(id)
);
