create table category (
    id bigint generated by default as identity primary key,
    name varchar(255),
    category_code varchar(255) not null,
    parent_category_id bigint,
    level integer not null,
    constraint uk_category_code unique (category_code),
    constraint fk_category_parent foreign key (parent_category_id) references category(id)
);
