create table product (
    id bigint generated by default as identity primary key,
    name varchar(255),
    slug varchar(255),
    description varchar(255),
    original_price numeric(19, 2),
    unit_price numeric(19, 2),
    discount_percentage double precision not null,
    stock double precision not null,
    lead_time_min_days integer not null,
    lead_time_max_days integer not null,
    product_type varchar(255),
    has_iva boolean not null,
    iva_percentage integer not null,
    num_ratings integer not null,
    category_id bigint,
    created_date timestamp not null,
    last_modified_date timestamp,
    created_by bigint not null,
    last_modified_by bigint,
    constraint uk_product_slug unique (slug),
    constraint fk_product_category foreign key (category_id) references category(id)
);

create table product_entity_images (
    product_entity_id bigint not null,
    images varchar(255),
    constraint fk_product_images_product foreign key (product_entity_id) references product(id)
);

create table review (
    id bigint generated by default as identity primary key,
    review_text varchar(255) not null,
    rating double precision not null,
    product_id bigint not null,
    user_id bigint not null,
    created_date timestamp not null,
    last_modified_date timestamp,
    created_by bigint not null,
    last_modified_by bigint,
    constraint fk_review_product foreign key (product_id) references product(id),
    constraint fk_review_user foreign key (user_id) references _user(id)
);

create table review_entity_images (
    review_entity_id bigint not null,
    images varchar(255),
    constraint fk_review_images_review foreign key (review_entity_id) references review(id)
);

create table wish_list_products (
    wish_list_entity_id bigint not null,
    products_id bigint not null,
    primary key (wish_list_entity_id, products_id),
    constraint fk_wish_list_products_wish_list foreign key (wish_list_entity_id) references wish_list(id),
    constraint fk_wish_list_products_product foreign key (products_id) references product(id)
);
