create table coupon (
    id bigint generated by default as identity primary key,
    code varchar(255),
    discount_percentage double precision not null,
    start_date date,
    end_date date,
    minimum_purchase_amount double precision not null,
    active boolean not null,
    created_date timestamp not null,
    last_modified_date timestamp,
    created_by bigint not null,
    last_modified_by bigint
);

create table _user_used_coupons (
    user_id bigint not null,
    used_coupons_id bigint not null,
    primary key (user_id, used_coupons_id),
    constraint fk_user_used_coupons_user foreign key (user_id) references _user(id),
    constraint fk_user_used_coupons_coupon foreign key (used_coupons_id) references coupon(id)
);
