create table cart (
    id bigint generated by default as identity primary key,
    user_id bigint,
    session_id varchar(255),
    subtotal numeric(19, 2),
    total_tax numeric(19, 2),
    discount_percentage numeric(19, 2),
    coupon_discount_amount numeric(19, 2),
    grand_total numeric(19, 2),
    quantity integer not null,
    coupon_code varchar(255),
    status varchar(255),
    created_date timestamp not null,
    last_modified_date timestamp,
    constraint fk_cart_user foreign key (user_id) references _user(id)
);

create table cart_item (
    id bigint generated by default as identity primary key,
    cart_id bigint,
    product_id bigint,
    quantity integer not null,
    original_price numeric(19, 2),
    unit_price numeric(19, 2),
    subtotal numeric(19, 2),
    tax_percentage integer not null,
    tax_amount numeric(19, 2),
    user_id bigint,
    lead_time_min_days integer not null,
    lead_time_max_days integer not null,
    created_date timestamp not null,
    last_modified_date timestamp,
    constraint fk_cart_item_cart foreign key (cart_id) references cart(id),
    constraint fk_cart_item_product foreign key (product_id) references product(id)
);
