create table orders (
    id bigint generated by default as identity primary key,
    order_id varchar(255),
    user_id bigint,
    session_id varchar(255),
    shipping_address_id bigint,
    subtotal numeric(19, 2),
    total_tax numeric(19, 2),
    discount_percentage numeric(19, 2),
    coupon_discount_amount numeric(19, 2),
    grand_total numeric(19, 2),
    order_status varchar(255),
    payment_status varchar(255),
    order_date timestamp,
    delivery_date timestamp,
    created_date timestamp not null,
    last_modified_date timestamp,
    constraint fk_orders_user foreign key (user_id) references _user(id),
    constraint fk_orders_shipping_address foreign key (shipping_address_id) references address(id)
);

create table order_item (
    id bigint generated by default as identity primary key,
    order_id bigint,
    product_id bigint,
    quantity integer not null,
    original_price numeric(19, 2),
    unit_price numeric(19, 2),
    subtotal numeric(19, 2),
    tax_percentage integer not null,
    tax_amount numeric(19, 2),
    user_id bigint,
    promised_lead_time_min_days integer not null,
    promised_lead_time_max_days integer not null,
    created_date timestamp not null,
    last_modified_date timestamp,
    constraint fk_order_item_order foreign key (order_id) references orders(id),
    constraint fk_order_item_product foreign key (product_id) references product(id)
);

create table payment (
    id bigint generated by default as identity primary key,
    order_id bigint not null,
    payment_id varchar(255),
    payment_url varchar(255),
    amount numeric(10, 2),
    currency varchar(255) not null,
    status varchar(255) not null,
    authorization_code varchar(255),
    transaction_status varchar(255),
    failure_reason varchar(255),
    created_date timestamp not null,
    last_modified_date timestamp,
    constraint uk_payment_payment_id unique (payment_id),
    constraint fk_payment_order foreign key (order_id) references orders(id)
);
