create table stock_reservation (
    id bigint generated by default as identity primary key,
    product_id bigint not null,
    product_name varchar(255) not null,
    order_id bigint not null,
    quantity integer not null,
    status varchar(20) not null,
    expires_at timestamp not null,
    created_date timestamp not null,
    last_modified_date timestamp,
    created_by bigint not null,
    last_modified_by bigint
);

create index idx_reservation_status_expires on stock_reservation (status, expires_at);
create index idx_reservation_order on stock_reservation (order_id);
create index idx_reservation_product on stock_reservation (product_id);
