create table oauth_code (
    code varchar(255) not null primary key,
    user_id bigint,
    created_at timestamp,
    expires_at timestamp,
    used boolean not null
);

create table refresh_token (
    id bigint generated by default as identity primary key,
    user_id bigint not null,
    family_id varchar(64) not null,
    token_hash varchar(128) not null,
    created_at timestamp not null,
    expires_at timestamp not null,
    revoked_at timestamp,
    replaced_by_token_hash varchar(128),
    constraint uk_refresh_token_hash unique (token_hash),
    constraint fk_refresh_token_user foreign key (user_id) references _user(id)
);

create index idx_refresh_token_hash on refresh_token (token_hash);
create index idx_refresh_token_family on refresh_token (user_id, family_id);
