spring:
  profiles:
    active: dev  # Load configurations from application-dev.yml
springdoc:
  default-produces-media-type: application/json

server:
  servlet:
    context-path: /api/v1

trugarden:
  stock:
    max-made-to-order-quantity-per-order: 10