spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/trugarden_db
    username: chis
    password: chis
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update  # Hibernate will automatically update the database schema to match the entity classes. Only for dev
    show-sql: false
    properties:
      hibernate:
        format_sql: true  # Hibernate will print the SQL statements in a more human-readable format
    database: PostgreSQL  # This helps Hibernate understand how to interact with the database correctly.
    database-platform: org.hibernate.dialect.PostgreSQLDialect  # The dialect defines how Hibernate should communicate with the database, including SQL syntax and data types.

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

application:
  mailing:
    frontend:
      activation-url: http://localhost:4200/activate-account
  security:
    jwt:
      expiration: 86400000
      secret-key: 291d7b170fc96c6d87eed5d2fdf437eb20d508cc854cd34405818281c754bdab

server:
  port: 8088

payphone:
  token: "Bearer 443zdbuIG1KC03qg63NQE49UqxCVIMGLU3iXYZo4mQXbtoSsM1UX5jniJw0JGnD-2i5V0bZi0Y82yWDIUX847lXYeEQD6-iBMizEsv1Z6-xfJmKstjqHr0xNsDY9cZtiSZ_iffUtnmJSN-daWp6e8TyplFUo5x8wgK9-fFe280p8e6S2nTnVCy110f97J14nAekb9tinN053XzKEo_asfRJEMb99xLUNQPuDf9DHLfjCsWrM9ryU2M8QVyq-1InD_uy2bodwPi7W-RRLmy55tcW9soqpC4xmWMCshbK7yf-Y4Cr1ATWCJesMUjcfX4pk5TADaA"
  base-url: "https://pay.payphonetodoesposible.com/api"
  store-id: "cef216f3-2189-4724-9b71-f3d84ee71890"
  callback-url: "http://localhost:3000/response"
  cancel-url: "http://localhost:3000/cancel"

trugarden:
  email:
    provider: ${MAIL_PROVIDER}
    from: ${MAIL_FROM}
    api-key: ${MAIL_API_KEY}